api_platform:
    resource: .
    type: api_platform
    prefix: /api

app_swagger_ui:
    path: /api/be1287/doc
    methods: GET
    defaults: { _controller: api_platform.swagger.action.ui, area: default }