controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_platform:
  resource: ../src/Controller/
  type: annotation
  prefix: /api
  
authentication_token:
    path: /authentication_token
    methods: [ 'POST' ]