controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute

api_platform:
  resource: ../src/Controller/
  type: attribute
  prefix: /api
  
authentication_token:
    path: /authentication_token
    methods: [ 'POST' ]

verify_email:
    path: /verify-email
    controller: App\Controller\EmailVerificationController::verifyEmail
    methods: GET