controllers:
    resource: ../src/Controller/
<<<<<<< HEAD
    type: attribute
=======
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_platform:
  resource: ../src/Controller/
  type: annotation
  prefix: /api
  
authentication_token:
    path: /authentication_token
    methods: [ 'POST' ]
>>>>>>> 5194f2fd (Initial commit)
